[application]
name = "RoboAMO"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[application.tools]
binaryen = { wasm-opt = true }

[web.app]
# HTML title tag content
title = "RoboAMO"
base_path = "/roboamo/"

[web.watcher]
reload_html = true
index_on_404 = true

# include `assets` in web platform
[web.resource.dev]
# Additional CSS style files
style = ["input.css"]
# Additional JavaScript files
script = []
# Add this line to serve demo files as static assets
assets = ["assets"]